# BrainSpark Frontend - Cloud Build Configuration
# File: frontend/cloudbuild.yaml

steps:
  # Step 1: Install dependencies and build
  - name: 'node:20-alpine'
    id: 'install-build'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci
        npm run build
    dir: 'frontend'
    env:
      - 'VITE_API_URL=${_API_URL}'
      - 'VITE_APP_URL=${_APP_URL}'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '--build-arg'
      - 'VITE_APP_URL=${_APP_URL}'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'frontend'
    waitFor: ['install-build']

  # Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--port=80'
    waitFor: ['push-image']

  # Step 5: Map custom domain (if not already mapped)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'map-domain'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking domain mapping for ${_DOMAIN}..."
        gcloud run domain-mappings describe --domain=${_DOMAIN} --region=${_REGION} 2>/dev/null || \
        gcloud run domain-mappings create --service=${_SERVICE_NAME} --domain=${_DOMAIN} --region=${_REGION} || \
        echo "Domain mapping already exists or skipped"
    waitFor: ['deploy-cloud-run']

  # Step 6: Verify deployment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'verify-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        echo "Checking health at $${SERVICE_URL}"
        curl -f "$${SERVICE_URL}" || exit 1
        echo "Frontend deployment verified successfully!"
    waitFor: ['deploy-cloud-run']

# Substitution variables with defaults
substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'brainspark'
  _SERVICE_NAME: 'brainspark-web'
  _API_URL: 'https://api.brainspark.siggmatreders.com'
  _APP_URL: 'https://brainspark.siggmatreders.com'
  _DOMAIN: 'brainspark.siggmatreders.com'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '5'
  _MEMORY: '256Mi'
  _CPU: '1'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build artifacts
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'

# Timeout for the entire build
timeout: '1200s'

# Tags for organization
tags:
  - 'brainspark'
  - 'frontend'
  - 'web'
