# Simplified Cloud Build - Backend Only
# For debugging deployment issues

steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Push backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api'
    waitFor: ['build-backend']

  # Deploy backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brainspark-api'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${BUILD_ID}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--add-cloudsql-instances=${PROJECT_ID}:${_REGION}:brainspark-db'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT},DEFAULT_AI_MODEL=${_DEFAULT_AI_MODEL}'
      - '--update-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest,GROK_API_KEY=grok-api-key:latest,JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest'
    waitFor: ['push-backend']

substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'brainspark'
  _ENVIRONMENT: 'prod'
  _DEFAULT_AI_MODEL: 'claude'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${BUILD_ID}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'

timeout: '1200s'
