# ============================================================
# BrainSpark - Complete Automated Cloud Build
# ============================================================
# Single command deployment: gcloud builds submit --config=cloudbuild-auto.yaml
# ============================================================

steps:

  # ============================================================
  # STEP 0: SETUP PREREQUISITES (APIs, Registry, Service Account)
  # ============================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-prerequisites'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=============================================="
        echo "   BrainSpark - Automated Deployment"
        echo "   Project: ${PROJECT_ID}"
        echo "=============================================="

        # Enable required APIs
        echo "Enabling APIs..."
        gcloud services enable \
          run.googleapis.com \
          artifactregistry.googleapis.com \
          secretmanager.googleapis.com \
          cloudbuild.googleapis.com \
          --quiet

        # Create Artifact Registry if not exists
        echo "Setting up Artifact Registry..."
        gcloud artifacts repositories describe ${_REPO_NAME} \
          --location=${_REGION} 2>/dev/null || \
        gcloud artifacts repositories create ${_REPO_NAME} \
          --repository-format=docker \
          --location=${_REGION} \
          --description="BrainSpark Docker images" \
          --quiet

        # Create service account if not exists
        echo "Setting up Service Account..."
        gcloud iam service-accounts describe \
          brainspark-backend@${PROJECT_ID}.iam.gserviceaccount.com 2>/dev/null || \
        gcloud iam service-accounts create brainspark-backend \
          --display-name="BrainSpark Backend Service" \
          --quiet

        # Grant secret access to service account
        gcloud projects add-iam-policy-binding ${PROJECT_ID} \
          --member="serviceAccount:brainspark-backend@${PROJECT_ID}.iam.gserviceaccount.com" \
          --role="roles/secretmanager.secretAccessor" \
          --quiet 2>/dev/null || true

        # Check if secrets exist, create placeholders if not
        echo "Checking secrets..."
        if ! gcloud secrets describe anthropic-api-key --quiet 2>/dev/null; then
          echo "WARNING: anthropic-api-key secret missing!"
          echo "Create it with: echo 'YOUR_KEY' | gcloud secrets create anthropic-api-key --data-file=-"
        fi

        if ! gcloud secrets describe jwt-secret --quiet 2>/dev/null; then
          echo "Creating jwt-secret..."
          openssl rand -base64 64 | gcloud secrets create jwt-secret --data-file=- --quiet 2>/dev/null || true
        fi

        echo "✓ Prerequisites complete"

  # ============================================================
  # STEP 1: BUILD BACKEND IMAGE
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Backend API..."
        docker build \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${SHORT_SHA:-latest} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest \
          -f backend/Dockerfile \
          backend/
        echo "✓ Backend image built"
    waitFor: ['setup-prerequisites']

  # ============================================================
  # STEP 2: BUILD FRONTEND IMAGE
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Frontend..."
        docker build \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${SHORT_SHA:-latest} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest \
          --build-arg VITE_API_URL=https://api.brainspark.siggmatreders.com \
          --build-arg VITE_APP_URL=https://brainspark.siggmatreders.com \
          -f frontend/Dockerfile \
          frontend/
        echo "✓ Frontend image built"
    waitFor: ['setup-prerequisites']

  # ============================================================
  # STEP 3: PUSH BACKEND IMAGE
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api'
    waitFor: ['build-backend']

  # ============================================================
  # STEP 4: PUSH FRONTEND IMAGE
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web'
    waitFor: ['build-frontend']

  # ============================================================
  # STEP 5: DEPLOY BACKEND TO CLOUD RUN
  # ============================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Backend API to Cloud Run..."

        # Check if anthropic-api-key exists
        if gcloud secrets describe anthropic-api-key --quiet 2>/dev/null; then
          SECRET_FLAG="--update-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest,JWT_SECRET=jwt-secret:latest"
        else
          echo "WARNING: Deploying without secrets (anthropic-api-key missing)"
          SECRET_FLAG=""
        fi

        gcloud run deploy brainspark-api \
          --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${SHORT_SHA:-latest} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=10 \
          --memory=1Gi \
          --cpu=2 \
          --timeout=300 \
          --concurrency=100 \
          --set-env-vars="ENVIRONMENT=production,APP_URL=https://brainspark.siggmatreders.com,API_URL=https://api.brainspark.siggmatreders.com,CORS_ORIGINS=https://brainspark.siggmatreders.com" \
          $${SECRET_FLAG} \
          --service-account=brainspark-backend@${PROJECT_ID}.iam.gserviceaccount.com \
          --quiet

        echo "✓ Backend deployed"
    waitFor: ['push-backend']

  # ============================================================
  # STEP 6: DEPLOY FRONTEND TO CLOUD RUN
  # ============================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Frontend to Cloud Run..."

        gcloud run deploy brainspark-web \
          --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${SHORT_SHA:-latest} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=5 \
          --memory=256Mi \
          --cpu=1 \
          --timeout=60 \
          --concurrency=80 \
          --port=80 \
          --quiet

        echo "✓ Frontend deployed"
    waitFor: ['push-frontend']

  # ============================================================
  # STEP 7: GET DEPLOYMENT URLS & SUMMARY
  # ============================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deployment-summary'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ""
        echo "=============================================="
        echo "   DEPLOYMENT COMPLETE"
        echo "=============================================="
        echo ""

        BACKEND_URL=$(gcloud run services describe brainspark-api --region=${_REGION} --format='value(status.url)' 2>/dev/null || echo "pending")
        FRONTEND_URL=$(gcloud run services describe brainspark-web --region=${_REGION} --format='value(status.url)' 2>/dev/null || echo "pending")

        echo "   Cloud Run URLs:"
        echo "   - API:     $${BACKEND_URL}"
        echo "   - Web:     $${FRONTEND_URL}"
        echo ""
        echo "   Production URLs (after DNS setup):"
        echo "   - App:     https://brainspark.siggmatreders.com"
        echo "   - API:     https://api.brainspark.siggmatreders.com"
        echo ""
        echo "   DNS Records Required:"
        echo "   - brainspark.siggmatreders.com     CNAME  ghs.googlehosted.com"
        echo "   - api.brainspark.siggmatreders.com CNAME  ghs.googlehosted.com"
        echo ""
        echo "=============================================="
    waitFor: ['deploy-backend', 'deploy-frontend']

# ============================================================
# SUBSTITUTIONS
# ============================================================
substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'brainspark'

# ============================================================
# BUILD OPTIONS
# ============================================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true

# Images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'

# Build timeout (15 minutes)
timeout: '900s'

tags:
  - 'brainspark'
  - 'automated'
