# Simplified Cloud Build - Frontend Only

steps:
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '--build-arg'
      - 'VITE_APP_URL=${_APP_URL}'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  # Push frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web'
    waitFor: ['build-frontend']

  # Deploy frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brainspark-web'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${BUILD_ID}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--port=8080'
    waitFor: ['push-frontend']

substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'brainspark'
  _API_URL: 'https://brainspark-api-37t2wofhfa-el.a.run.app'
  _APP_URL: 'https://brainspark.siggmatreders.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${BUILD_ID}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'

timeout: '1200s'
