# BrainSpark Backend - Cloud Build Configuration
# File: backend/cloudbuild.yaml

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=300'
      - '--set-env-vars=ENVIRONMENT=${_ENVIRONMENT}'
      - '--set-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest,JWT_SECRET=jwt-secret:latest,DATABASE_URL=database-url:latest'
      - '--vpc-connector=${_VPC_CONNECTOR}'
      - '--vpc-egress=private-ranges-only'
    waitFor: ['push-image']

  # Step 4: Run database migrations (if needed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Database migrations would run here"
        # gcloud run jobs execute brainspark-migrations --region=${_REGION} --wait
    waitFor: ['deploy-cloud-run']

  # Step 5: Verify deployment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'verify-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        echo "Checking health at $${SERVICE_URL}/health"
        curl -f "$${SERVICE_URL}/health" || exit 1
        echo "Backend deployment verified successfully!"
    waitFor: ['deploy-cloud-run']

# Substitution variables with defaults
substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'brainspark'
  _SERVICE_NAME: 'brainspark-api'
  _ENVIRONMENT: 'prod'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _MEMORY: '1Gi'
  _CPU: '2'
  _VPC_CONNECTOR: 'brainspark-connector'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build artifacts
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'

# Timeout for the entire build
timeout: '1200s'

# Tags for organization
tags:
  - 'brainspark'
  - 'backend'
  - 'api'
